[package]
name = "discordbot"
version = "0.1.0"
authors = ["Marcin Grzywaczewski <killavus@gmail.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
error-chain = "0.11.0"
dotenv = "0.10.1"
chrono = "0.4.0"
